# Column renames applied after spark.table(...) and before joins.
# Keys under column_renames are source Spark column names; values are new names.

sales_transactions:
  fqn: samples.bakehouse.sales_transactions
  column_renames:
    dateTime: trans_timestamp



sales_suppliers:
  fqn: samples.bakehouse.sales_suppliers
  column_renames:
    name: supplier_name
    ingredient: supplier_ingredient
    continent: supplier_continent
    city: supplier_city
    district: supplier_district
    size: supplier_size
    longitude: supplier_longitude
    latitude: supplier_latitude
    approved: supplier_approved

sales_customers:
  fqn: samples.bakehouse.sales_customers
  column_renames:
    first_name: customer_first_name
    last_name: customer_last_name
    address: customer_address
    city: customer_city
    state: customer_state
    postal_zip_code: customer_postal_zip_code
    country: customer_country
    continent: customer_continent
    email_address: customer_email_address
    phone_number: customer_phone_number
    gender: customer_gender



sales_franchises:
  fqn: samples.bakehouse.sales_franchises
  column_renames:
    name: franchise_name
    city: franchise_city
    district: franchise_district
    zipcode: franchise_zipcode
    country: franchise_country
    size: franchise_size
    longitude: franchise_longitude
    latitude: franchise_latitude

media_gold_reviews_chunked:
  fqn: samples.bakehouse.media_gold_reviews_chunked
  column_renames:
    review_date: chunked_review_date
    review_uri: chunked_review_uri
    chunk_id: chunked_id

media_customer_reviews:
  fqn: samples.bakehouse.media_customer_reviews
  column_renames:
    new_id: review_new_id
