-- Delta mart DDL (run via bundle job after {{TARGET_FQN}} substitution).
-- Aligned with samples.bakehouse joins in src/ingest_data.py (core path, no media).

CREATE TABLE IF NOT EXISTS {{TARGET_FQN}} (
  transactionID BIGINT COMMENT 'merge key',
  customerID BIGINT,
  franchiseID BIGINT,
  trans_timestamp TIMESTAMP,
  product STRING,
  quantity BIGINT,
  unitPrice BIGINT,
  totalPrice BIGINT,
  paymentMethod STRING,
  cardNumber BIGINT,
  customer_name STRING,
  email_address STRING,
  phone_number STRING,
  address STRING,
  city STRING,
  state STRING,
  postal_zip_code STRING,
  country STRING,
  continent STRING,
  franchise_name STRING,
  franchise_city STRING,
  franchise_district STRING,
  franchise_zipcode STRING,
  franchise_country STRING,
  franchise_size STRING,
  franchise_longitude DOUBLE,
  franchise_latitude DOUBLE,
  supplierID BIGINT,
  chunked_review_date TIMESTAMP,
  chunked_text  STRING,
  chunked_id string,
  chunked_review_uri string,
  review string,
  review_date TIMESTAMP,
  review_new_id INT
) USING DELTA
partitioned by (trans_timestamp);
