-- Delta mart DDL (run via bundle job after {{TARGET_FQN}} substitution).
-- Aligned with config/ingest.yaml renames + src/ingest_data.py _core_denormalized_through_suppliers (no media joins).

CREATE TABLE IF NOT EXISTS {{TARGET_FQN}} (
  transactionID BIGINT COMMENT 'merge key',
  customerID BIGINT,
  franchiseID BIGINT,
  supplierID BIGINT,
  trans_timestamp TIMESTAMP,
  product STRING,
  quantity BIGINT,
  unitPrice BIGINT,
  totalPrice BIGINT,
  paymentMethod STRING,
  cardNumber BIGINT,
  customer_first_name STRING,
  customer_last_name STRING,
  customer_address STRING,
  customer_city STRING,
  customer_state STRING,
  customer_postal_zip_code STRING,
  customer_country STRING,
  customer_continent STRING,
  customer_email_address STRING,
  customer_phone_number STRING,
  customer_gender STRING,
  franchise_name STRING,
  franchise_city STRING,
  franchise_district STRING,
  franchise_zipcode STRING,
  franchise_country STRING,
  franchise_size STRING,
  franchise_longitude DOUBLE,
  franchise_latitude DOUBLE,
  supplier_name STRING,
  supplier_ingredient STRING,
  supplier_continent STRING,
  supplier_city STRING,
  supplier_district STRING,
  supplier_size STRING,
  supplier_longitude DOUBLE,
  supplier_latitude DOUBLE,
  supplier_approved BOOLEAN,
  chunked_review_date TIMESTAMP,
  chunked_text  STRING,
  chunked_id string,
  chunked_review_uri string,
  review string,
  review_date TIMESTAMP,
  review_new_id INT
) USING DELTA
partitioned by (trans_timestamp);
